AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - config/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
    - Guardfile
    - Rakefile
    - config.ru
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - app/models/appointment.rb

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*

Style/FormatStringToken:
  Exclude:
    - spec/services/notification_factory_spec.rb

Style/SymbolArray:
  Exclude:
    - app/controllers/**/*

Style/IfUnlessModifier:
  Exclude:
    - app/models/appointment.rb
