name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0

      - name: Clean bundle
        run: bundle clean --force

      - name: setup test db
        run: bundle exec rails db:create db:schema:load db:migrate db:seed RAILS_ENV=test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: lapin_test
          POSTGRES_PASSWORD: lapin_test
          POSTGRES_DB: lapin_test

      # Runs a single command using the runners shell
      - name: Spec suite
        run: rspec

      # Runs a set of commands using the runners shell
      - name: Deploy staging
        run: bin/deploy-staging
